{% set name = "pyfilemanager" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyfilemanager-{{ version }}.tar.gz
  sha256: e826ac9c78d0726f3dde9fa40d3138ef7bbf0cab91f85c403bfc2265993bc689

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.7,<4.0

test:
  imports:
    - pyfilemanager
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/praneethnamburi/pyfilemanager
  summary: Easy to use file search and file path management in python.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://pyfilemanager.readthedocs.io
  dev_url: https://github.com/praneethnamburi/pyfilemanager

extra:
  recipe-maintainers:
    - praneethnamburi
